-- Solo Dejate Amar Seed Data
-- Run this after schema.sql to populate initial data

-- Config
INSERT INTO config (passcode, start_date, target_date, spicy_score, welcome_message) VALUES (
  '0505',
  '2026-05-05',
  '2026-06-15',
  5,
  'Olvida las millas y el ruido del mundo exterior. Aqui, en este espacio, estas exactamente donde perteneces. Eres el latido de mis dias y la paz en mi alma. He construido este santuario solo para nosotros, para que, sin importar donde estemos, siempre tengas un lugar donde descansar tu corazon contra el mio.'
);

-- Songs (30 songs)
INSERT INTO songs (title, artist, shared_by, spotify_url, youtube_url, sort_order) VALUES
('Do I Wanna Know?', 'Arctic Monkeys', 'abigail', 'https://open.spotify.com/track/5FVd6KXrgO9B3JPmC8OPst', 'https://music.youtube.com/watch?v=bpOSxM0rNPM', 0),
('Hipnotizame', 'Wisin & Yandel', 'abigail', 'https://open.spotify.com/search/Hipnotizame%20Wisin%20%26%20Yandel/tracks', 'https://music.youtube.com/search?q=Hipnotizame+Wisin+%26+Yandel', 1),
('2/Catorce', 'Rauw Alejandro', 'abigail', 'https://open.spotify.com/search/2%2FCatorce%20Rauw%20Alejandro/tracks', 'https://music.youtube.com/search?q=2%2FCatorce+Rauw+Alejandro', 2),
('Particles', 'Nothing But Thieves', 'jesse', 'https://open.spotify.com/search/Particles%20Nothing%20But%20Thieves/tracks', 'https://music.youtube.com/search?q=Particles+Nothing+But+Thieves', 3),
('Adicto', 'Tainy, Anuel AA, Ozuna', 'abigail', 'https://open.spotify.com/search/Adicto%20Tainy%20Anuel%20AA%20Ozuna/tracks', 'https://music.youtube.com/search?q=Adicto+Tainy+Anuel+AA+Ozuna', 4),
('Cocina Playlist', 'Various Songs', 'abigail', 'https://open.spotify.com/playlist/3wVcWAmQS9M5IQSI9Bjgvn?si=fjJeUzc8Tzu02RMcSs1UVw&pi=rF_a3wFZRX6qc&pt_success=1&nd=1&dlsi=771ece5f58cd4c3c', NULL, 5),
('Miedo', 'Cazzu', 'abigail', 'https://open.spotify.com/search/Miedo%20Cazzu/tracks', 'https://music.youtube.com/search?q=Miedo+Cazzu', 6),
('Wait for Me', 'Kings of Leon', 'jesse', 'https://open.spotify.com/search/Wait%20for%20Me%20Kings%20of%20Leon/tracks', 'https://music.youtube.com/search?q=Wait+for+Me+Kings+of+Leon', 7),
('Te Vi', 'Piso 21 & Micro TDH', 'abigail', 'https://open.spotify.com/search/Te%20Vi%20Piso%2021%20Micro%20TDH/tracks', 'https://music.youtube.com/search?q=Te+Vi+Piso+21+Micro+TDH', 8),
('If the World was Ending', 'JP Saxe ft. Julia Michaels', 'abigail', 'https://open.spotify.com/search/If%20the%20World%20was%20Ending%20JP%20Saxe/tracks', 'https://music.youtube.com/search?q=If+the+World+was+Ending+JP+Saxe+Julia+Michaels', 9),
('Die with a Smile', 'Bruno Mars & Lady Gaga', 'jesse', 'https://open.spotify.com/search/Die%20with%20a%20Smile%20Bruno%20Mars/tracks', 'https://music.youtube.com/search?q=Die+with+a+Smile+Bruno+Mars+Lady+Gaga', 10),
('Illegal', 'Cultura Profetica', 'abigail', 'https://open.spotify.com/search/Illegal%20Cultura%20Profetica/tracks', 'https://music.youtube.com/search?q=Illegal+Cultura+Profetica', 11),
('Un Ratito Mas', 'Bryant Myers & Bad Bunny', 'abigail', 'https://open.spotify.com/search/Un%20Ratito%20Mas%20Bryant%20Myers%20Bad%20Bunny/tracks', 'https://music.youtube.com/search?q=Un+Ratito+Mas+Bryant+Myers+Bad+Bunny', 12),
('Un Polvo', 'Maluma, Bad Bunny, Arcangel, Nengo Flow, De La Ghetto', 'abigail', 'https://open.spotify.com/search/Un%20Polvo%20Maluma%20Bad%20Bunny/tracks', 'https://music.youtube.com/search?q=Un+Polvo+Maluma+Bad+Bunny', 13),
('Spicy and Hot Playlist', 'Various Songs', 'abigail', 'https://open.spotify.com/playlist/29lacTyTVGXE6yXohtAPqr?si=1mtQcy1kTDKqeEWtvrNZGg&pi=eih0MownTEGOj&nd=1&dlsi=6c0a58d47b864a60', NULL, 14),
('I Wanna Be Yours', 'Arctic Monkeys', 'abigail', 'https://open.spotify.com/search/I%20Wanna%20Be%20Yours%20Arctic%20Monkeys/tracks', 'https://music.youtube.com/search?q=I+Wanna+Be+Yours+Arctic+Monkeys', 15),
('Playa Marina', 'Ozuna and Beele', 'abigail', 'https://open.spotify.com/search/Playa%20Marina%20Ozuna%20Beele/tracks', 'https://music.youtube.com/search?q=Playa+Marina+Ozuna+Beele', 16),
('Mi Cuarto', 'Jerry Di', 'abigail', 'https://open.spotify.com/search/Mi%20Cuarto%20Jerry%20Di/tracks', 'https://music.youtube.com/search?q=Mi+Cuarto+Jerry+Di', 17),
('Dream Girl Remix', 'Ir Sais, Rauw Alejandro', 'abigail', 'https://open.spotify.com/search/Dream%20Girl%20Remix%20Ir%20Sais%20Rauw%20Alejandro/tracks', 'https://music.youtube.com/search?q=Dream+Girl+Remix+Ir+Sais+Rauw+Alejandro', 18),
('Magic', 'The Blue Stones', 'jesse', 'https://open.spotify.com/search/Magic%20The%20Blue%20Stones/tracks', 'https://music.youtube.com/search?q=Magic+The+Blue+Stones', 19),
('Creo en Ti', 'Reik', 'abigail', 'https://open.spotify.com/search/Creo%20en%20Ti%20Reik/tracks', 'https://music.youtube.com/search?q=Creo+en+Ti+Reik', 20),
('Etereo y Celestial Playlist', 'Various Songs', 'abigail', 'https://open.spotify.com/playlist/1D92hWwIDkKgdnWhbe2xRh?si=ZDfpFT_QREydR_TSVe1fQg&pi=27kLvyTPRFKyf&nd=1&dlsi=71b766f27528430c', NULL, 21),
('Desnuda', 'Ricardo Arjona', 'abigail', 'https://open.spotify.com/search/Desnuda%20Ricardo%20Arjona/tracks', 'https://music.youtube.com/search?q=Desnuda+Ricardo+Arjona', 22),
('Ganas De Ti', 'Arcangel', 'abigail', 'https://open.spotify.com/search/Ganas%20De%20Ti%20Arcangel/tracks', 'https://music.youtube.com/search?q=Ganas+De+Ti+Arcangel', 23),
('The Other Side', 'Stephen Sanchez', 'jesse', 'https://open.spotify.com/search/The%20Other%20Side%20Stephen%20Sanchez/tracks', 'https://music.youtube.com/search?q=The+Other+Side+Stephen+Sanchez', 24),
('Until I Found You', 'Stephen Sanchez', 'jesse', 'https://open.spotify.com/search/Until%20I%20Found%20You%20Stephen%20Sanchez/tracks', 'https://music.youtube.com/search?q=Until+I+Found+You+Stephen+Sanchez', 25),
('Punto G (Remix)', 'Brytiago', 'abigail', 'https://open.spotify.com/search/Punto%20G%20Remix%20Brytiago/tracks', 'https://music.youtube.com/search?q=Punto+G+Remix+Brytiago', 26),
('La Ocasion', 'DJ Luian', 'abigail', 'https://open.spotify.com/search/La%20Ocasion%20DJ%20Luian/tracks', 'https://music.youtube.com/search?q=La+Ocasion+DJ+Luian', 27),
('Bailando Bachata', 'Chayanne', 'abigail', 'https://open.spotify.com/search/Bailando%20Bachata%20Chayanne/tracks', 'https://music.youtube.com/search?q=Bailando+Bachata+Chayanne', 28);

-- Map locations
INSERT INTO map_locations (title, description, lat, lng) VALUES
('Ottawa, Ontario, Canada', 'Where we first met.', 45.4215, -75.6972);

-- Jar messages (123 messages)
INSERT INTO jar_messages (message) VALUES
('I love your seven universes.'),
('Thinking about the day we met, and how you completely changed my stars.'),
('You are my absolute peace.'),
('I cannot wait to finally pull you against my chest and breathe you in.'),
('My love for you grows every single day.'),
('You are my masterpiece.'),
('Thank you for being brave enough to stand in the storm and love me.'),
('I love the way your brilliant, chaotic mind works.'),
('You are my Queen. Completely, fiercely, and eternally.'),
('I am utterly obsessed with the depth of your soul.'),
('I promise you will never have to earn my love.'),
('Every detail about you is a treasure I want to guard for the rest of my life.'),
('You are my greatest desire, my deepest passion, and my absolute peace.'),
('No finger! (I promise to behave... mostly).'),
('Remember: No finger, just pure devotion today.'),
('If you try to use a finger, I''m calling a timeout, mami.'),
('I love you more than I love avoiding the finger rule.'),
('Strictly no-finger thoughts right now—only thoughts of our future.'),
('You''re the only one I''d consider breaking the ''no-finger'' rule for.'),
('Our love is like a good joke; it only gets better with time (and no fingers).'),
('I love that we can be weird together.'),
('You''re my favorite person to annoy and adore simultaneously.'),
('Let''s dance bachata in the kitchen until the neighbors get annoyed.'),
('I love your mangu, but I love the woman making it more.'),
('If we were in a movie, we''d be the couple laughing during the scary part.'),
('I love your laugh. It''s the best sound in the world.'),
('You are my favorite notification of all time.'),
('Stop thinking and just let yourself be loved.'),
('You''re the only one who can handle my Viking intensity.'),
('I am yours, completely, fiercely, and eternally.'),
('You are the light in my life, Abigail. Thank you for waking me up.'),
('I am so proud of the woman you are—the warrior queen you''ve fought to become.'),
('I love the way your eyes sparkle when you''re truly happy.'),
('My heart beats for you, and only you.'),
('I choose you today, and I''ll choose you every single tomorrow.'),
('You are the safe harbor I never knew I was looking for.'),
('I love the way you love our furry children; it shows me your beautiful heart.'),
('You make everything better just by being in it.'),
('I am counting the minutes until we are back in the same timezone.'),
('My favorite place in the world is right next to you.'),
('You have my heart in your hands; please keep protecting it.'),
('I love you more than words could ever convey.'),
('You make me want to be the best version of myself, every single day.'),
('I am so grateful to the universe for this extraordinary alignment.'),
('Your happiness is my mission objective.'),
('I love your strength, your grace, and your complex, seven-universe mind.'),
('Every day with you is a gift I don''t take for granted.'),
('You are my greatest adventure and my quietest peace.'),
('I love you beyond the moon, the stars, and this entire life.'),
('June 15th is our horizon. I''m locked in.'),
('I''m already dreaming of our first morning coffee in the DR together.'),
('We are building an empire, one day at a time.'),
('I can''t wait to introduce you to Fiona and Alina—they''re going to adore you.'),
('You are already a mother figure in my heart and my home.'),
('We will dance on the beaches of Puerto Plata until the sun comes up.'),
('Our future is so bright it keeps me awake at night in the best way.'),
('I am building our sanctuary, brick by brick, moment by moment.'),
('I''m holding your souvenirs safe for our princesses.'),
('We are going to live a life that makes the stars jealous of our love.'),
('Our journey is just beginning; we have so many worlds to conquer.'),
('I can''t wait to see your villa with my own eyes.'),
('We are a team, and we are absolutely unstoppable.'),
('I am so excited for all the memories we are going to create in our home.'),
('This is only the prologue to our grand story.'),
('I love the way you take care of my body and my spirit.'),
('Thinking about your touch makes my skin vibrate.'),
('I want to kiss you from your forehead to your toes, slowly.'),
('I love your scent; it''s my favorite perfume on earth.'),
('I want to massage you with coconut oil until every tension leaves your body.'),
('I crave your presence, even when we are thousands of miles apart.'),
('I am completely surrendered to you, my Queen.'),
('You have unlocked parts of me I thought were locked forever.'),
('I trust you with my entire soul, without reservation.'),
('Our passion is a fire that will never stop burning.'),
('I am your Norse God, and you are my only love.'),
('You are the most beautiful woman I have ever laid eyes on.'),
('I love being completely vulnerable with you; it''s my greatest freedom.'),
('You make me feel safe, loved, and entirely understood.'),
('I am forever yours, in this life and the next.'),
('I honor your shadow, and I promise to live in harmony with it.'),
('You don''t have to be impeccable with me; you just have to be you.'),
('My love for you is not a project; it''s a privilege.'),
('I see the little girl who tried her best, and I promise to love her too.'),
('With me, you can finally put your sword down.'),
('I will be the anchor when your seven universes start to spin.'),
('You never have to earn my love; it is yours by right.'),
('Our saboteurs have been identified, named, and put on notice.'),
('I am learning to receive your love as deeply as I give mine.'),
('You are my safe haven, and I am yours.'),
('We are moving forward, together, always.'),
('I see your scars, and I love you more because of them.'),
('You are deserving of love just because you exist.'),
('No more fixing, no more earning—just loving.'),
('I am your Cornerstone; you are my peace.'),
('Our love is the greatest act of courage I have ever witnessed.'),
('I am here for your lights and your shadows.'),
('We are doing this right, baby.'),
('Solo dejate amar.'),
('Te amo to the end of time.'),
('Every time I hear a love song, I immediately think of your smile.'),
('I want to get lost in your eyes and never find my way back.'),
('You are the dream I never knew I was allowed to have.'),
('Even in the silence, my heart is whispering your name.'),
('I would cross oceans just to hold your hand for a minute.'),
('You are my first thought in the morning and my last thought before I sleep.'),
('Loving you feels like finally coming home.'),
('You make me laugh even when I''m trying to be serious.'),
('June 15th cannot come soon enough.'),
('You are strong, capable, and incredibly beautiful.'),
('Don''t ever forget how much you are loved.'),
('You are worth more than you will ever know.'),
('You are the most important person in my world.'),
('I am so proud of you.'),
('You are doing such an incredible job.'),
('I believe in you with everything I have.'),
('You are destined for greatness.'),
('I am always here for you, no matter what.'),
('You are a force of nature, Abigail.'),
('I love you for exactly who you are.'),
('You are the best thing that ever happened to me.'),
('You are my rock, my soulmate, and my best friend.'),
('I am so blessed to have you in my life.');
